// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSRFCdtJq3o9B82Tc5_AWcSE7oluyTI5A',
    appId: '1:466945831786:web:b39bee3525dfa8b7502b13',
    messagingSenderId: '466945831786',
    projectId: 'yfl-mobile',
    authDomain: 'yfl-mobile.firebaseapp.com',
    storageBucket: 'yfl-mobile.firebasestorage.app',
    measurementId: 'G-K8NKQLY6PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQEzsCu--ayBWtPwzNRbp11xnQkFW5nE',
    appId: '1:466945831786:android:feee78dfae4b93f3502b13',
    messagingSenderId: '466945831786',
    projectId: 'yfl-mobile',
    storageBucket: 'yfl-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuppNRgX9pdGFeqh_tvSxyeFw5U8UquBY',
    appId: '1:466945831786:ios:81aeb93f943bd6a4502b13',
    messagingSenderId: '466945831786',
    projectId: 'yfl-mobile',
    storageBucket: 'yfl-mobile.firebasestorage.app',
    iosBundleId: 'com.example.yflMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuppNRgX9pdGFeqh_tvSxyeFw5U8UquBY',
    appId: '1:466945831786:ios:81aeb93f943bd6a4502b13',
    messagingSenderId: '466945831786',
    projectId: 'yfl-mobile',
    storageBucket: 'yfl-mobile.firebasestorage.app',
    iosBundleId: 'com.example.yflMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSRFCdtJq3o9B82Tc5_AWcSE7oluyTI5A',
    appId: '1:466945831786:web:b2ca303bc9a153db502b13',
    messagingSenderId: '466945831786',
    projectId: 'yfl-mobile',
    authDomain: 'yfl-mobile.firebaseapp.com',
    storageBucket: 'yfl-mobile.firebasestorage.app',
    measurementId: 'G-3NYMNJ6GGC',
  );
}
